title: K.Tierney
name: K.Tierney
email: k@krtierney.com
author: Kaitlyn Tierney
description: Web developer, writer, editor, photographer, ceramicist.
baseurl: ""
url: "https://www.krtierney.com"
twitter_username: krtierney
github_username: krtierney
linkedin_username: krtierney

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude: [vendor]
