title: K. Tierney
email: k@krtierney.com
description: Web developer, writer, editor, photographer.
baseurl: ""
url: "https://www.krtierney.com"
twitter_username: krtierney
github_username: krtierney
linkedin_username: krtierney
instagram_username: ktierney
google_analytics: UA-33302350-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude: [vendor]
