title: K.Tierney
email: k@krtierney.com
description: Web developer, writer, editor, photographer.
baseurl: ""
url: "https://www.krtierney.com"
twitter_username: krtierney
github_username: krtierney
linkedin_username: krtierney
instagram_username: ktierney

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude: [vendor]
